/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '046191' at '3/6/17 5:08 PM' with Gradle 3.2.1
 *
 * @author 046191, @date 3/6/17 5:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
